routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/', 'PagesController@inicio')->name('ini');
Route::get('/home', 'HomeController@index')->name('home');

//Protege las rutas para que solo se entre con registro
Route::group(['middleware' => 'auth'], function () {
	//Protege las rutas para que no se pueda regresar una vez que ya salio de la sesion
	Route::group(['middleware' => 'reglas'], function () {
		Route::get('lista','PagesController@listas')->name('list');
		Route::get('cambia','PagesController@cambios')->name('cambiar');
		Route::get('agrega','PagesController@agregare')->name('agregar');
		Route::get('perfil','PagesController@perfiles')->name('profile');
		Route::get('usuarios','PagesController@usuarios')->name('usuarios');
		Route::resource('subir','ImageUploadController' );
		Route::resource('regist', 'RegistroController');
		
		//rutas con JQuery
		Route::post('borrar', 'RegistroController@destroyer');
		Route::post('store', 'RegistroController@store');
		Route::post('update2', 'RegistroController@update2');
		
		//ruta para la tabla
		 Route::get('action', 'PagesController@registroList');
	});
});


Route::fallback(function() {
    return abort(404);
});

resources/views/vistas/agrega.blade.php
@extends('plantilla/plantilla')


@section('parte')

    <div class="container">
      <h1 class="display-4">Agrega</h1>
      <br></br>

      <form method="POST" action="{{action('RegistroController@store' )}}"  role="form">

        {{ csrf_field() }}
        <div class="form-row">
          <div class="col">
            <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Nombre">
          </div>
          <div class="col">
            <input type="text" class="form-control" id="apellidos" name="apePaterno" placeholder="Apellido Paterno">
          </div>
          <div class="col">
            <input type="text" class="form-control" id="apellidos" name="apeMaterno" placeholder="Apellido Materno">
          </div>
          <div class="col">
            <input type="text" class="form-control" id="email" name="email" placeholder="Email">
          </div><br></br> <br>
        </div>
        
        <button type="submit" class="btn btn-outline-secondary">Agrega</button>
      </form> 
    </div>

@endsection

resources/views/vistas/cambia.blade.php
@extends('plantilla/plantilla')


@section('parte')

    <div class="container">
      <h1 class="display-4">Cambia</h1>
      <br></br>  
      <form method="post"  action="{{route('regist.update', $registro->id)}}">
        @method('PATCH')
        {{csrf_field()}}
        <div class="form-row">
          <div class="col">
            <input type="text" class="form-control" placeholder="Nombre" name="nombre" value="{{$registro->nombre}}">
          </div>
          <div class="col">
            <input type="text" class="form-control" placeholder="Apellido Paterno" name="apePaterno" value="{{$registro->apePaterno}}">
          </div>
          <div class="col">
            <input type="text" class="form-control" placeholder="Apellido Materno" name="apeMaterno" value="{{$registro->apeMaterno}}">
          </div>
          <div class="col">
            <input type="text" class="form-control" placeholder="Email"  name ="email" value="{{$registro->email}}">
          </div>
          <br></br><br>
        </div>
        <input type="submit"  value="Actualizar" class="btn btn-outline-secondary">
        <br><br>
      </form>
    </div>

@endsection

resources/views/vistas/control_usuarios.blade.php
@extends('plantilla/plantilla')

@section('parte')

<div class="container">
      <h1 class="display-4">Control de Usuarios</h1>
      <br></br>
</div>

@endsection

resources/views/vistas/index.blade.php
@extends('plantilla/plantilla')

@section('parte')

    <div class="container">
      <h1 class="display-4">Inicio</h1>
    </div>
    
@endsection

 

resources/views/vistas/lista.blade.php
@extends('plantilla/plantilla')
 
@section('parte')
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
  <div  class="container">
      <h1 class="display-4">Lista</h1>
      <br>
    <button data-toggle="modal" data-target="#regnue"  id="reg_nue"  class="btn btn-info" >Nuevo Registro</button>
    <br></br>
    <br></br>
    @include('modal/nuevoregistro')
    <div id="contenedor_principal">
      <div  id="table_data">
          @include('vistas/tabla_registros')
      </div> 
    </div>
    <!-- paginacion metodo  de pages controler -->
  
  </div>



@endsection

resources/views/vistas/perfil.blade.php
@extends('plantilla/plantilla')

@section('parte')

    <div class="container">
      <h1 class="display-4">Perfil</h1>
      <br><br>
      <div>
        <div class="profile-userpic" id="avatar_actual">
          <img src="{{ Storage::url($user[0]->avatar)}}" style="width: 50px; height: 50px">
        </div>
        <h2>{{ Auth::user()->name }}</h2>
        <h2>{{ Auth::user()->email }}</h2>
      <!-- droppzone imagenes -->
        <div>
          <form method="POST" action="{{route('subir.store')}}" class="dropzone" id="dropzone" enctype="multipart/form-data">
              {{ csrf_field() }}
              <div class="dz-message">
                  Arrastra o selecciona una Imagen
              </div>
          </form>
        </div>
      </div>
    </div>
    
@endsection

resources/views/vistas/tabla_registros.blade.php
<table class="table"  id="user_table">
      <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Nombre</th>
            <th scope="col">Apellido Materno</th>
            <th scope="col">Apellidos Paterno</th>
            <th scope="col">E-mail</th>
            @if(@Auth::user()->hasAnyRole(['user', 'admin']))
            <th scope="col">Cambia</th>
            <th scope="col">Cambia 2</th>
            @endif
            @if(@Auth::user()->hasRole( 'admin'))
            <th scope="col">Elimina</th>
            @endif
          </tr>
      </thead>
       @include('modal/editregistro')
      <!-- <tbody>
        @include('modal/editregistro')
      </tbody> -->
      <!-- @foreach($registro as $regis)    
      <tr>
        <th scope="row"> {{ $regis-> id}}</th>
        <td>{{$regis->nombre}}</td>
        <td> {{$regis->apePaterno}}  {{$regis->apeMaterno}} </td>
        <td>{{$regis->email}}</td>
        @if(@Auth::user()->hasAnyRole(['user', 'admin']))
        <td>
          <a href="{{ route('regist.edit', $regis->id)}}" class="btn btn-success"></a>
        </td>
        <td>
          <button type="button" data-id="{{$regis->id}}" data-nombre="{{$regis->nombre}}" data-apepaterno="{{$regis->apePaterno}}" data-apematerno="{{$regis->apeMaterno}}" data-email="{{$regis->email}}" data-toggle="modal" data-target="#edit"  class="btn btn-warning"></button>
            @include('modal/editregistro')
        </td>
        @endif
        @if(@Auth::user()->hasRole( 'admin'))
        <td>
          <form action="{{action('RegistroController@destroy', $regis->id)}}" method="post">
            {{csrf_field()}}
            <input name="_method" type="hidden" value="DELETE">
            <button class="btn btn-danger btn-xs" type="submit"><span class="glyphicon glyphicon-trash"></span></button>
          </form>          
        </td>
       @endif
      </tr> 
      @endforeach() -->
</table>